--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Tuvqlu/Your-own-Hive
build-by-default: true
branches:
- main 
projects:
  YourOwnHive:
    path: ""
    libs:
      - src: AIPTU/Commando/Commando
        version: ^3.1.0
    lint:
      phpstan: false 
...
